name: Release to AUR

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print pkgver
        run: echo "::set-output name=PKGVER::"`printf "%s.r%s.%s" "$(grep -F '__version__ =' epy.py | awk -F\" '{print $2}')" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"`
        id: pkgver
      - name: test
        run: echo "pkgver: ${{ steps.pkgver.PKGVER }}"
