name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    paths:
      - epy.py
      - tests/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: abatilo/actions-poetry@v2.0.0
      - name: Install dev dependencies
        run: poetry install --no-root
      - name: Run tests
        run: |
          poetry run coverage run --include=epy.py -m pytest -vv tests
          poetry run coverage report

